package tools.mapletools;

import provider.wz.WZFiles;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

/**
 * ShopItemDumper — UmamiMS AIO Shop Generator
 *
 * Reads the handbook txt files and generates SQL INSERT statements to populate
 * Frederick's AIO shop (shop IDs 6000–6707) with valid v83 item IDs.
 *
 * HOW TO RUN:
 *   Run from the project root (same directory as the handbook/ folder).
 *   Output is written to: tools/output/shop_items.sql
 *
 * HOW TO APPLY:
 *   "C:\Program Files\MySQL\MySQL Server 9.7\bin\mysql.exe" -u root -p cosmic < tools/output/shop_items.sql
 *
 * NOTES:
 *   - USE-type shops (throwing stars, bullets, arrows) may crash v83 clients. Test before
 *     enabling them in the NPC menu.
 *   - All items are priced at 1 meso. Edit DEFAULT_PRICE to change.
 *   - Each shop is capped at MAX_PER_SHOP items to keep client memory stable.
 *   - Shops that share an equip category (e.g. all Hat shops) intentionally contain the
 *     same item pool — the client enforces class/stat equip restrictions in-game.
 */
public class ShopItemDumper {

    private static final Path OUTPUT_FILE   = ToolConstants.getOutputFile("shop_items.sql");
    private static final String HB          = ToolConstants.HANDBOOK_PATH;
    private static final int    MAX_PER_SHOP = 150;
    private static final int    DEFAULT_PRICE = 1;

    // prefix (itemId / 10000) → list of item IDs
    private static final Map<Integer, List<Integer>> equipItems  = new LinkedHashMap<>();
    private static final Map<Integer, List<Integer>> useItems    = new LinkedHashMap<>();
    private static final Map<Integer, List<Integer>> setupItems  = new LinkedHashMap<>();
    private static final Map<Integer, List<Integer>> cashItems   = new LinkedHashMap<>();
    private static final Map<Integer, List<Integer>> tamingItems = new LinkedHashMap<>();

    // itemId → name, populated when loading Weapon.txt for Maple-weapon filtering
    private static final Map<Integer, String> weaponNames = new LinkedHashMap<>();

    // Item IDs confirmed to exist in the local WZ files — used to filter out cross-version items
    private static final Set<Integer> wzValidIds = new HashSet<>();

    // itemId → reqJob bitmask from Character.wz XML
    // 0=any, 1=Warrior, 2=Magician, 4=Archer, 8=Thief, 16=Pirate
    private static final Map<Integer, Integer> itemReqJob = new HashMap<>();

    // itemId → required level from Character.wz XML (for level-ascending sort)
    private static final Map<Integer, Integer> itemReqLevel = new HashMap<>();

    // equip item IDs flagged cash=1 in Character.wz XML (NX cosmetics)
    private static final Set<Integer> cashEquipIds = new HashSet<>();

    // ─────────────────────────────────────────────────────────────────────────
    //  Entry point
    // ─────────────────────────────────────────────────────────────────────────

    public static void main(String[] args) throws IOException {
        loadWzValidIds();

        System.out.println("[ShopItemDumper] Loading handbook files...");
        loadEquipFiles();
        loadFile(HB + "/Use.txt",          useItems);
        loadFile(HB + "/Setup.txt",        setupItems);
        loadFile(HB + "/Cash.txt",         cashItems);
        loadFile(HB + "/Pet.txt",          cashItems);   // pet IDs (5000xxx) go into cash pool
        loadFile(HB + "/Equip/Taming.txt", tamingItems);

        Files.createDirectories(OUTPUT_FILE.getParent());

        try (PrintWriter out = new PrintWriter(
                new BufferedWriter(new OutputStreamWriter(
                        Files.newOutputStream(OUTPUT_FILE), StandardCharsets.UTF_8)))) {

            out.println("-- ============================================================");
            out.println("-- UmamiMS AIO Shop — shopitems population");
            out.println("-- Generated by ShopItemDumper");
            out.println("-- Apply: mysql -u root -p cosmic < tools/output/shop_items.sql");
            out.println("-- ============================================================");
            out.println();
            out.println("SET FOREIGN_KEY_CHECKS = 0;");
            out.println();

            // Register any new shop IDs added since the last full run
            out.println("-- Register new shop IDs (Magician/Archer/Pirate Tops+Bottoms)");
            out.println("INSERT IGNORE INTO shops (shopid, npcid) VALUES");
            out.println("  (6207, 9030000), (6208, 9030000),");
            out.println("  (6308, 9030000), (6309, 9030000),");
            out.println("  (6506, 9030000), (6507, 9030000);");
            out.println();

            // ── Common ──────────────────────────────────────────────────────
            // reqJob == 0 items only — usable by any class
            writeShop(out, 6000, "Common — Hats",                   fromEquipCommon(100));
            writeShop(out, 6001, "Common — Earrings",               fromEquipCommon(103));
            writeShop(out, 6002, "Common — Necklaces & Accessories", fromEquipCommon(112, 111));
            writeShop(out, 6003, "Common — Capes",                  fromEquipCommon(110));
            writeShop(out, 6004, "Common — Overalls",               fromEquipCommon(105));
            writeShop(out, 6005, "Common — Gloves",                 fromEquipCommon(108));
            writeShop(out, 6006, "Common — Shields",                fromEquipCommon(109));
            writeShop(out, 6007, "Common — Shoes",                  fromEquipCommon(107));
            writeShop(out, 6008, "Common — Maple Weapons",          mapleWeapons());
            writeShop(out, 6009, "Common — Level 0 Weapons",        level0Weapons());

            // ── Warrior (reqJob bit 1) ───────────────────────────────────────
            writeShop(out, 6100, "Warrior — Hats",      fromEquipForJob(1, 100));
            writeShop(out, 6101, "Warrior — Tops",      fromEquipForJob(1, 104));
            writeShop(out, 6102, "Warrior — Bottoms",   fromEquipForJob(1, 106));
            writeShop(out, 6103, "Warrior — Overalls",  fromEquipForJob(1, 105));
            writeShop(out, 6104, "Warrior — Gloves",    fromEquipForJob(1, 108));
            writeShop(out, 6105, "Warrior — Shields",   fromEquipForJob(1, 109));
            writeShop(out, 6106, "Warrior — Shoes",     fromEquipForJob(1, 107));
            // Weapons are class-exclusive by item prefix — no reqJob filter needed
            writeShop(out, 6107, "Warrior — 1H Axes",   fromEquip(131));
            writeShop(out, 6108, "Warrior — 2H Axes",   fromEquip(141));
            writeShop(out, 6109, "Warrior — 1H BWs",    fromEquip(132));
            writeShop(out, 6110, "Warrior — 2H BWs",    fromEquip(142));
            writeShop(out, 6111, "Warrior — 1H Swords", fromEquip(130));
            writeShop(out, 6112, "Warrior — 2H Swords", fromEquip(140));
            writeShop(out, 6113, "Warrior — Spears",    fromEquip(143));
            writeShop(out, 6114, "Warrior — Pole Arms", fromEquip(144));

            // ── Magician (reqJob bit 2) ──────────────────────────────────────
            writeShop(out, 6200, "Magician — Hats",     fromEquipForJob(2, 100));
            writeShop(out, 6201, "Magician — Overalls", fromEquipForJob(2, 105));
            writeShop(out, 6202, "Magician — Gloves",   fromEquipForJob(2, 108));
            writeShop(out, 6203, "Magician — Shields",  fromEquipForJob(2, 109));
            writeShop(out, 6204, "Magician — Shoes",    fromEquipForJob(2, 107));
            writeShop(out, 6205, "Magician — Wands",    fromEquip(137));
            writeShop(out, 6206, "Magician — Staffs",   fromEquip(138));
            writeShop(out, 6207, "Magician — Tops",     fromEquipForJob(2, 104));
            writeShop(out, 6208, "Magician — Bottoms",  fromEquipForJob(2, 106));

            // ── Archer (reqJob bit 4) ────────────────────────────────────────
            writeShop(out, 6300, "Archer — Hats",      fromEquipForJob(4, 100));
            writeShop(out, 6301, "Archer — Overalls",  fromEquipForJob(4, 105));
            writeShop(out, 6302, "Archer — Gloves",    fromEquipForJob(4, 108));
            writeShop(out, 6303, "Archer — Shoes",     fromEquipForJob(4, 107));
            writeShop(out, 6304, "Archer — Bows",      fromEquip(145));
            writeShop(out, 6305, "Archer — CrossBows", fromEquip(146));
            writeShop(out, 6306, "Archer — Arrows",    Arrays.asList(2060000,2060001,2060002,2060003,2060004,2060005,2060006));
            writeShop(out, 6307, "Archer — Bolts",     Arrays.asList(2061000,2061001,2061002,2061003,2061004,2061005,2061006));
            writeShop(out, 6308, "Archer — Tops",      fromEquipForJob(4, 104));
            writeShop(out, 6309, "Archer — Bottoms",   fromEquipForJob(4, 106));

            // ── Thief (reqJob bit 8) ─────────────────────────────────────────
            writeShop(out, 6400, "Thief — Hats",           fromEquipForJob(8, 100));
            writeShop(out, 6401, "Thief — Tops",            fromEquipForJob(8, 104));
            writeShop(out, 6402, "Thief — Bottoms",         fromEquipForJob(8, 106));
            writeShop(out, 6403, "Thief — Overalls",        fromEquipForJob(8, 105));
            writeShop(out, 6404, "Thief — Gloves",          fromEquipForJob(8, 108));
            writeShop(out, 6405, "Thief — Shields",         fromEquipForJob(8, 109));
            writeShop(out, 6406, "Thief — Shoes",           fromEquipForJob(8, 107));
            writeShop(out, 6407, "Thief — Daggers",         fromEquip(133));
            writeShop(out, 6408, "Thief — Claws",           fromEquip(147));
            writeShop(out, 6409, "Thief — Throwing Stars",
                      Arrays.asList(2070000,2070001,2070002,2070003,2070004,2070005,2070006,2070007));

            // ── Pirate (reqJob bit 16) ───────────────────────────────────────
            writeShop(out, 6500, "Pirate — Hats",     fromEquipForJob(16, 100));
            writeShop(out, 6501, "Pirate — Overalls", fromEquipForJob(16, 105));
            writeShop(out, 6502, "Pirate — Gloves",   fromEquipForJob(16, 108));
            writeShop(out, 6503, "Pirate — Shoes",    fromEquipForJob(16, 107));
            writeShop(out, 6504, "Pirate — Weapons",  fromEquip(148, 149));
            writeShop(out, 6505, "Pirate — Bullets & Capsules",
                      Arrays.asList(2330000,2330001,2330002,2330003,2330004));
            writeShop(out, 6506, "Pirate — Tops",     fromEquipForJob(16, 104));
            writeShop(out, 6507, "Pirate — Bottoms",  fromEquipForJob(16, 106));

            // ── NX Items (cash equips only — fromEquipCash excludes stat gear) ──
            writeShop(out, 6600, "NX — Hats",             fromEquipCash(100));
            writeShop(out, 6601, "NX — Earrings",          fromEquipCash(103));
            writeShop(out, 6602, "NX — Face Accessories",  fromEquipCash(101));
            writeShop(out, 6603, "NX — Tops",              fromEquipCash(104));
            writeShop(out, 6604, "NX — Bottoms",           fromEquipCash(106));
            writeShop(out, 6605, "NX — Capes",             fromEquipCash(110));
            writeShop(out, 6606, "NX — Overalls",          fromEquipCash(105));
            writeShop(out, 6607, "NX — Rings",             fromEquipCash(111));
            writeShop(out, 6608, "NX — Gloves",            fromEquipCash(108));
            writeShop(out, 6609, "NX — Shields",           fromEquipCash(109));
            writeShop(out, 6610, "NX — Shoes",             fromEquipCash(107));
            writeShop(out, 6611, "NX — Weapons",           fromEquipCash(130,133,134,135,140,145,146,147,148,149));
            writeShop(out, 6612, "NX — Throwing Stars",    fromUse(207));
            writeShop(out, 6613, "NX — Pets",              fromCash(500));
            writeShop(out, 6614, "NX — Pet Misc",          fromEquipCash(180));
            writeShop(out, 6615, "NX — Emotions",          fromCash(502));
            writeShop(out, 6616, "NX — Effects",           fromCash(501));
            writeShop(out, 6617, "NX — Accessories",       fromEquipCash(112, 111, 103));
            writeShop(out, 6618, "NX — Player FM Stores",  fromCash(510));

            // ── ETC ─────────────────────────────────────────────────────────
            // Messengers = megaphones (507x), super megaphones (5072x), item megaphones (5076x)
            writeShop(out, 6700, "ETC — Messengers",
                      Arrays.asList(5070000,5070001,5070002,5070003,5070004,
                                    5071000,5071001,5072000,5076000));
            // Mega/Gach/Rocks: gachapon tickets (5220x), teleport rocks (5040x), morph cards (5041x)
            writeShop(out, 6701, "ETC — Mega/Gach/Rocks/Morphs",
                      Arrays.asList(5220000,5220001,5220002,5220003,
                                    5040000,5040001,5040002,5040100,
                                    5041000,5041001,5041010));
            // Buffs & Potions — confirmed v83 potion IDs only
            writeShop(out, 6703, "ETC — Buffs & Potions",
                      Arrays.asList(2000000,2000001,2000002,2000003,2000004,2000005,2000006,
                                    2010000,2010001,2010002,2010003,
                                    2022000,2022001,2022002,2022003,2022004,2022005,
                                    2022014,2022015,2022016,2022017,2022018,2022019,
                                    2022024,2022025,2022026,2022027));
            writeShop(out, 6704, "ETC — Scrolls",              fromUse(204));
            writeShop(out, 6705, "ETC — Summoning Sacks",      fromUse(228));
            writeShop(out, 6706, "ETC — Chairs",
                      Arrays.asList(3010000,3010001,3010002,3010003,3010004,3010005,3010006,
                                    3010007,3010008,3010009,3010010,3010011,3010012,3010013,3010014));
            // Mounts: saddle equips only — mount bodies (1902x) don't render in shop UI
            writeShop(out, 6707, "ETC — Mounts",
                      Arrays.asList(1912000,1912001,1912002,1912003,1912004,1912005,1912006,1912007));

            out.println();
            out.println("SET FOREIGN_KEY_CHECKS = 1;");
            out.println();
            out.println("-- Done.");
        }

        System.out.println("[ShopItemDumper] Complete! Output: " + OUTPUT_FILE.toAbsolutePath());
        System.out.println("[ShopItemDumper] Apply with:");
        System.out.println("  \"C:\\Program Files\\MySQL\\MySQL Server 9.7\\bin\\mysql.exe\" -u root -p cosmic < "
                + OUTPUT_FILE.toAbsolutePath());
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  WZ validator — builds the set of item IDs that actually exist in WZ
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Scans Character.wz and Item.wz to collect every item ID present in the local WZ files.
     * Only these IDs will appear in the generated SQL — anything else would crash the v83 client.
     */
    private static void loadWzValidIds() throws IOException {
        System.out.println("[ShopItemDumper] Scanning WZ files for valid item IDs...");

        // Character.wz — equip items. Each equip is a file named XXXXXXXX.img.xml
        // Skip files directly in the Character.wz root (those aren't items)
        File charWz = new File(WZFiles.CHARACTER.getFilePath());
        if (charWz.isDirectory()) {
            for (File subDir : charWz.listFiles()) {
                if (subDir.isDirectory()) {
                    scanWzDirectory(subDir);
                }
            }
        } else {
            System.out.println("[ShopItemDumper] WARN: Character.wz not found at " + charWz.getAbsolutePath());
        }

        // Item.wz — USE/SETUP/ETC items. Each item is also a file named XXXXXXXX.img.xml
        File itemWz = new File(WZFiles.ITEM.getFilePath());
        if (itemWz.isDirectory()) {
            scanWzDirectory(itemWz);
        } else {
            System.out.println("[ShopItemDumper] WARN: Item.wz not found at " + itemWz.getAbsolutePath());
        }

        System.out.println("[ShopItemDumper] WZ scan complete — " + wzValidIds.size() + " valid item IDs found.");
    }

    private static void scanWzDirectory(File dir) {
        File[] files = dir.listFiles();
        if (files == null) return;
        for (File f : files) {
            if (f.isDirectory()) {
                scanWzDirectory(f);
            } else if (f.getName().endsWith(".img.xml")) {
                int id = parseWzFilename(f.getName());
                if (id > 0) {
                    wzValidIds.add(id);
                    // Parse equip metadata for class/level/cash filtering
                    if (id >= 1000000 && id < 2000000) {
                        parseEquipXml(f, id);
                    }
                }
            }
        }
    }

    private static int parseWzFilename(String filename) {
        try {
            return Integer.parseInt(filename.replace(".img.xml", ""));
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    /**
     * Single-pass read of a Character.wz equip XML.
     * Extracts reqJob, reqLevel, and cash flag into the shared maps/sets.
     */
    private static void parseEquipXml(File xmlFile, int id) {
        int reqJob = 0, reqLevel = 0;
        boolean isCash = false;
        try (BufferedReader br = new BufferedReader(
                new InputStreamReader(new FileInputStream(xmlFile), StandardCharsets.UTF_8))) {
            String line;
            int lineCount = 0;
            while ((line = br.readLine()) != null && lineCount < 300) {
                lineCount++;
                if (line.contains("reqJob"))          reqJob   = extractXmlInt(line);
                else if (line.contains("reqLevel"))   reqLevel = extractXmlInt(line);
                else if (line.contains("name=\"cash\"")) isCash = (extractXmlInt(line) == 1);
            }
        } catch (Exception ignored) {}
        itemReqJob.put(id, reqJob);
        itemReqLevel.put(id, reqLevel);
        if (isCash) cashEquipIds.add(id);
    }

    /** Extracts the integer from a WZ XML attribute: value="N" */
    private static int extractXmlInt(String line) {
        try {
            int vi = line.indexOf("value=\"") + 7;
            int ve = line.indexOf("\"", vi);
            if (vi > 6 && ve > vi) return Integer.parseInt(line.substring(vi, ve));
        } catch (Exception ignored) {}
        return 0;
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  File loaders
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Loads all Equip handbook files into equipItems.
     * Also populates weaponNames (itemId → name) for Maple-weapon filtering.
     */
    private static void loadEquipFiles() throws IOException {
        String[] equipFiles = {
            "Cap", "Coat", "Pants", "Longcoat", "Glove", "Shield",
            "Shoes", "Cape", "Accessory", "Ring", "PetEquip", "Weapon"
        };
        for (String f : equipFiles) {
            String path = HB + "/Equip/" + f + ".txt";
            File file = new File(path);
            if (!file.exists()) {
                System.out.println("[ShopItemDumper] Skipping missing file: " + path);
                continue;
            }
            boolean isWeapon = f.equals("Weapon");
            try (BufferedReader br = new BufferedReader(
                    new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8))) {
                String line;
                while ((line = br.readLine()) != null) {
                    line = line.trim();
                    if (line.isEmpty()) continue;
                    int[] parsed = parseLine(line);
                    if (parsed == null) continue;
                    int itemId = parsed[0];
                    int prefix = itemId / 10000;
                    equipItems.computeIfAbsent(prefix, k -> new ArrayList<>()).add(itemId);
                    if (isWeapon) {
                        // Store name for Maple-weapon filtering
                        int dash1 = line.indexOf(" - ");
                        if (dash1 >= 0) {
                            int dash2 = line.indexOf(" - ", dash1 + 3);
                            String name = dash2 >= 0
                                ? line.substring(dash1 + 3, dash2).trim()
                                : line.substring(dash1 + 3).trim();
                            weaponNames.put(itemId, name);
                        }
                    }
                }
            }
            System.out.println("[ShopItemDumper] Loaded: " + path);
        }
    }

    /**
     * Generic loader — reads a handbook file and adds items to the target map.
     * Format per line: "itemId - name - description"
     */
    private static void loadFile(String path, Map<Integer, List<Integer>> target) throws IOException {
        File file = new File(path);
        if (!file.exists()) {
            System.out.println("[ShopItemDumper] Skipping missing file: " + path);
            return;
        }
        try (BufferedReader br = new BufferedReader(
                new InputStreamReader(new FileInputStream(file), StandardCharsets.UTF_8))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;
                int[] parsed = parseLine(line);
                if (parsed == null) continue;
                int prefix = parsed[0] / 10000;
                target.computeIfAbsent(prefix, k -> new ArrayList<>()).add(parsed[0]);
            }
        }
        System.out.println("[ShopItemDumper] Loaded: " + path);
    }

    /**
     * Parses "itemId - name - ..." and returns [itemId] or null on failure.
     */
    private static int[] parseLine(String line) {
        int dash = line.indexOf(" - ");
        if (dash < 0) return null;
        try {
            int itemId = Integer.parseInt(line.substring(0, dash).trim());
            return new int[]{itemId};
        } catch (NumberFormatException e) {
            return null;
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Item list builders
    // ─────────────────────────────────────────────────────────────────────────

    private static List<Integer> fromEquip(int... prefixes) {
        return gather(equipItems, prefixes);
    }

    /**
     * Non-cash items equippable by ANY class (reqJob == 0, cash != 1).
     * Used for Common shops — plain stat gear any job can wear; NX cosmetics excluded.
     */
    private static List<Integer> fromEquipCommon(int... prefixes) {
        List<Integer> base = gather(equipItems, prefixes);
        List<Integer> result = new ArrayList<>();
        for (int id : base) {
            Integer rj = itemReqJob.get(id);
            if ((rj == null || rj == 0) && !cashEquipIds.contains(id)) result.add(id);
        }
        return result;
    }

    /**
     * Cash equips only (cash == 1 in WZ).
     * Used for NX shops — purely cosmetic items from the cash catalogue.
     */
    private static List<Integer> fromEquipCash(int... prefixes) {
        List<Integer> base = gather(equipItems, prefixes);
        List<Integer> result = new ArrayList<>();
        for (int id : base) {
            if (cashEquipIds.contains(id)) result.add(id);
        }
        return result;
    }

    /**
     * Items that REQUIRE a specific job class (reqJob & classBit != 0).
     * Used for class-specific shops — only items exclusive to that class appear.
     * reqJob bitmask: 1=Warrior, 2=Magician, 4=Archer, 8=Thief, 16=Pirate
     */
    private static List<Integer> fromEquipForJob(int classBit, int... prefixes) {
        List<Integer> base = gather(equipItems, prefixes);
        List<Integer> result = new ArrayList<>();
        for (int id : base) {
            Integer rj = itemReqJob.get(id);
            if (rj != null && rj != 0 && (rj & classBit) != 0) result.add(id);
        }
        return result;
    }

    private static List<Integer> fromUse(int... prefixes) {
        return gather(useItems, prefixes);
    }

    private static List<Integer> fromSetup(int... prefixes) {
        return gather(setupItems, prefixes);
    }

    private static List<Integer> fromCash(int... prefixes) {
        return gather(cashItems, prefixes);
    }

    private static List<Integer> fromTaming(int... prefixes) {
        return gather(tamingItems, prefixes);
    }

    private static List<Integer> gather(Map<Integer, List<Integer>> source, int... prefixes) {
        List<Integer> result = new ArrayList<>();
        for (int prefix : prefixes) {
            List<Integer> items = source.get(prefix);
            if (items != null) result.addAll(items);
        }
        return result;
    }

    /** Filters Weapon.txt items whose name contains "Maple". */
    private static List<Integer> mapleWeapons() {
        List<Integer> result = new ArrayList<>();
        for (Map.Entry<Integer, String> entry : weaponNames.entrySet()) {
            if (entry.getValue().contains("Maple")) {
                result.add(entry.getKey());
            }
        }
        return result;
    }

    /**
     * Known v83 Level-0 weapons — equippable by any class with no stat/level requirement.
     * Expand this list as needed based on in-game testing.
     */
    private static List<Integer> level0Weapons() {
        return Arrays.asList(
            1302000, // Sword
            1402000, // Two-handed Sword
            1312004, // Axe
            1412004, // Two-handed Axe
            1322005, // Blunt Weapon
            1422005, // Two-handed Blunt Weapon
            1332000, // Dagger
            1342000, // Wand
            1352000, // Staff
            1452000, // Bow
            1462000, // Crossbow
            1472000, // Claw
            1482000, // Knuckle
            1492000  // Gun
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  SQL writer
    // ─────────────────────────────────────────────────────────────────────────

    private static void writeShop(PrintWriter out, int shopId, String label, List<Integer> items) {
        out.printf("-- Shop %d: %s%n", shopId, label);

        if (items.isEmpty()) {
            out.printf("-- (no items found for shop %d — populate manually)%n%n", shopId);
            System.out.printf("[ShopItemDumper] WARN: shop %d (%s) has no items%n", shopId, label);
            return;
        }

        // Filter WZ-valid items — equip items only (1xxxxxxx).
        // USE/SETUP/Cash items (2xxxxxxx, 3xxxxxxx, 5xxxxxxx) are stored in batch XML files in Item.wz,
        // not as individual files, so they won't appear in wzValidIds and must not be filtered.
        List<Integer> wzFiltered = new ArrayList<>();
        int skipped = 0;
        for (int id : new LinkedHashSet<>(items)) {
            boolean isEquip = (id >= 1000000 && id < 2000000);
            if (isEquip && !wzValidIds.isEmpty() && !wzValidIds.contains(id)) {
                skipped++;
            } else {
                wzFiltered.add(id);
            }
        }
        if (skipped > 0) {
            System.out.printf("[ShopItemDumper] Shop %d: filtered %d items not in WZ (kept %d of %d)%n",
                    shopId, skipped, wzFiltered.size(), items.size());
        }

        // Deduplicate, sort by reqLevel ascending (then itemId as tiebreaker), and cap.
        // Items not in itemReqLevel (USE/cash items) default to 0 → sort by itemId only.
        List<Integer> sorted = new ArrayList<>(new LinkedHashSet<>(wzFiltered));
        sorted.sort((a, b) -> {
            int la = itemReqLevel.getOrDefault(a, 0);
            int lb = itemReqLevel.getOrDefault(b, 0);
            return la != lb ? Integer.compare(la, lb) : Integer.compare(a, b);
        });
        if (sorted.size() > MAX_PER_SHOP) {
            System.out.printf("[ShopItemDumper] Shop %d: capped at %d (had %d)%n",
                    shopId, MAX_PER_SHOP, sorted.size());
            sorted = sorted.subList(0, MAX_PER_SHOP);
        }

        out.printf("DELETE FROM shopitems WHERE shopid = %d;%n", shopId);
        out.printf("INSERT INTO shopitems (shopid, itemid, price, pitch, position) VALUES%n");

        for (int i = 0; i < sorted.size(); i++) {
            int pos = 104 + (i * 4);
            boolean last = (i == sorted.size() - 1);
            out.printf("  (%d, %d, %d, 0, %d)%s%n",
                    shopId, sorted.get(i), DEFAULT_PRICE, pos, last ? ";" : ",");
        }
        out.println();

        System.out.printf("[ShopItemDumper] Shop %d: %d items%n", shopId, sorted.size());
    }

    private static void writeHeader(PrintWriter out) {
        // intentionally left as method stub — header written inline in main
    }
}
